name: dev
channels:
  - conda-forge
  - defaults
  - mro
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - matplotlib
  - scikit-learn
  - beautifulsoup4
  - requests
  - pytest
  - seaborn
  - statsmodels
  - tensorflow
  - pyyaml
  - tensorflow-probability
  - ipython
  - flask
  - pillow
  - pip
  - imageio
  - pip:
      - db-sqlite3
      - pycryptodomex
      - pytest-mpl
      - pytest-cov
      - ulid
      - pynvml
      - ulid-py
      - soundfile
